### ISSUE TITLE
Add more songs

### ISSUE THREAD

**Issue by pradeepgangwar** [OrionStar25/Alarm#1]
@OrionStar25 Although this works fine but I think more songs can be added. IMO songs of dinchak pooja should be added :stuck_out_tongue: . Those songs can really work as an alarm whereas other songs in the current list are pleasant and do not sound like alarm :worried: .
Can we do this?

**Comment by OrionStar25** [comment]
Yes, go ahead! Also another suggestion would be to comment the names of songs being added to avoid repetition. :P

**Comment by pradeepgangwar** [comment]
Ok, I will open a PR soon. :+1:
